# Generated by Django 5.0.1 on 2024-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
